# Generated by Django 6.0.7 on 2026-07-21 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifyCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="手机号")),
                ("code", models.CharField(max_length=6, verbose_name="验证码")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="是否已使用")),
            ],
            options={
                "db_table": "verify_code",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="账号是否启用"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default="", max_length=11, verbose_name="手机号"),
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "login_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="登录时间"),
                ),
                (
                    "ip_address",
                    models.CharField(default="", max_length=50, verbose_name="IP地址"),
                ),
                (
                    "login_type",
                    models.CharField(
                        default="password", max_length=20, verbose_name="登录方式"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myApp.user"
                    ),
                ),
            ],
            options={
                "db_table": "login_log",
            },
        ),
    ]
