# Generated by Django 6.0.7 on 2026-07-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_verifycode_user_is_active_user_phone_loginlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobinfo",
            name="pratice",
            field=models.BooleanField(default=False, verbose_name="是否为实习单位"),
        ),
    ]
